apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraperapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: scraperapp
  template:
    metadata:
      labels:
        app: scraperapp
    spec:
      containers:
      - name: scraperapp
        image: firefox-splinter:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5005
        volumeMounts:
        - name: flasklogs
          mountPath: /var/log/flask
        - name: videos
          mountPath: /downloads
        env:
        - name: DD_AGENT_SERVICE_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: DD_AGENT_SERVICE_PORT
          value: '8126'
        - name: DOGSTATSD_HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: DD_LOGS_INJECTION
          value: 'true'
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-user
              key: token
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-password
              key: token
      volumes:
        - hostPath:
            path: /var/log/flask
          name: flasklogs
        - hostPath:
            path: /media/stankley/Samsung_T5/downloaded-videos
          name: videos
---
apiVersion: v1
kind: Service
metadata:
  name: scraperapp
spec:
  selector:
    app: scraperapp
  ports:
  - name: http
    protocol: TCP
    port: 5005
  type: NodePort
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: cm-datadog-confd
  namespace: default
data:
  flasklogs.yaml: |-
    init_config:
    instances:
    logs:
    - type: file
      path: /var/log/flask/mylog.json
      service: flask
      source: python
      sourcecategory: sourcecode 
