apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraperapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scraperapp
  template:
    metadata:
      labels:
        app: scraperapp
      annotations:
        com.datadoghq.com.ad.logs: '[{"source": "python", "service": "scraper-service"}]'
    spec:
      containers:
      - name: scraperapp
        image: burningion/firefox-splinter-scraper:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5005
        volumeMounts:
        - name: videos
          mountPath: /downloads
        env:
        - name: DATADOG_TRACE_AGENT_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: DD_TRACE_AGENT_PORT
          value: '8126'
        - name: DOGSTATSD_HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: DD_LOGS_INJECTION
          value: 'true'
        - name: DD_TRACE_ANALYTICS_ENABLED
          value: 'true'
        - name: DATADOG_SERVICE_NAME
          value: 'scraper-service'
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-user
              key: token
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-password
              key: token
      volumes:
        - hostPath:
            path: /media/stankley/Samsung_T5/downloaded-videos
          name: videos
---
apiVersion: v1
kind: Service
metadata:
  name: scraperapp
spec:
  selector:
    app: scraperapp
  ports:
  - name: http
    protocol: TCP
    port: 5005
  type: NodePort
